### ISSUE TITLE
Creating new user using HTTP POST yields 500 error page.

### ISSUE THREAD

**Issue by prasetya** [kobotoolbox/kobo-docker#101]
Hi Team, I have deployed kobo-docker to DigitalOcean and it's working well. Manual user registration from the website works, however creating new user using HTTP POST yield 500 error page as a result and `error: [Errno 111] Connection refused` in the server log.

CURL command:
```
curl -X POST -i \
-H "Content-Type: application/json" \
-H "Authorization: Basic <user:pass>" \
https://kobocat.pmap3kobo.tk/api/v1/profiles \
-d '{"username":"testuser","name":"Test","email":"testuser@email.com"}'
```

Server log:
```
kobocat_1         | ERROR 2017-02-09 00:25:46,897 base 124 140094834779968 Internal Server Error: /api/v1/profiles
kobocat_1         | Traceback (most recent call last):
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
kobocat_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
kobocat_1         |     return func(*args, **kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
kobocat_1         |     return view_func(*args, **kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
kobocat_1         |     return self.dispatch(request, *args, **kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
kobocat_1         |     response = self.handle_exception(exc)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
kobocat_1         |     response = handler(request, *args, **kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
kobocat_1         |     self.perform_create(serializer)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
kobocat_1         |     serializer.save()
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 191, in save
kobocat_1         |     self.instance = self.create(validated_data)
kobocat_1         |   File "./onadata/libs/serializers/user_profile_serializer.py", line 117, in create
kobocat_1         |     send_email=True)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/registration/models.py", line 114, in create_inactive_user
kobocat_1         |     registration_profile.send_activation_email(site, request)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/registration/models.py", line 369, in send_activation_email
kobocat_1         |     email_message.send()
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 303, in send
kobocat_1         |     return self.get_connection(fail_silently).send_messages([self])
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
kobocat_1         |     new_conn_created = self.open()
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 58, in open
kobocat_1         |     self.connection = connection_class(self.host, self.port, **connection_params)
kobocat_1         |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
kobocat_1         |     (code, msg) = self.connect(host, port)
kobocat_1         |   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
kobocat_1         |     self.sock = self._get_socket(host, port, self.timeout)
kobocat_1         |   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
kobocat_1         |     return socket.create_connection((host, port), timeout)
kobocat_1         |   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
kobocat_1         |     raise err
kobocat_1         | error: [Errno 111] Connection refused
```

Content of `envfiles/smtp.txt`:
```
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.mailtrap.io
EMAIL_PORT=2525
EMAIL_HOST_USER=<from mailtrap.io>
EMAIL_HOST_PASSWORD=<from mailtrap.io>
DEFAULT_FROM_EMAIL=info@pmap3kobo.tk
```

However creating the user manually works well and the activation email is sent (tested with SendGrid and Mailtrap). I'm using the latest master commit and I have restarted the docker-compose process multiple times.

Any help is appreciated :) Thank you very much.

**Comment by jnm** [comment]
KoBoCAT has legacy user-creation code, but it isn't used anymore (and we should remove it). If you need to create users programmatically, try doing it through KPI:
1. Go to `https://[YOUR KPI DOMAIN]/admin/kpi/authorizedapplication/`;
1. Log in as a superuser when prompted;
1. Click "Add authorized application";
1. Type a name, make note of the `Key`, and click "Save";
1. Modify your `curl` command:
```
curl -X POST -i \
-H "Content-Type: application/json" \
-H 'Authorization: Token [YOUR KEY FROM PREVIOUS STEP]' \
https://[YOUR KPI DOMAIN]/authorized_application/users/ \
-d '{"username":"testuser","password":"testpass","first_name":"Test","last_name":"User","email":"mustbe@valid.com"}'
```

**Comment by prasetya** [comment]
It works! Thank you :)
