### ISSUE TITLE
Error Install advanced options + On a server

### ISSUE THREAD

**Issue by dpadron** [kobotoolbox/kobo-docker#244]
Do you want to see advanced options?
        1) Yes
        2) No
[2]: 1
What kind of installation do you need?
        1) On your workstation
        2) On a server
[2]: 2
Please choose which network interface you want to use?
Traceback (most recent call last):
  File "run.py", line 66, in <module>
    run()
  File "run.py", line 26, in run
    current_config = config.build()
  File "/opt/kobo-install/helpers/config.py", line 211, in build
    self.__detect_network()
  File "/opt/kobo-install/helpers/config.py", line 404, in __detect_network
    interfaces = Network.get_local_interfaces()
  File "/opt/kobo-install/helpers/network.py", line 55, in get_local_interfaces
    names = array.array('B', MAX_BYTES * FILL_CHAR)
TypeError: must be char, not unicode

**Comment by noliveleger** [comment]
Related to `kobo-install`.
